import type { WorkflowTemplate } from '../../types/workflow.js';
import { orchestratorDefenceDisclosurePrompt } from '../../agents/prompts/orchestrator-defence-disclosure.js';
import { workflowRegistry } from '../registry.js';

export const defenceDisclosureTemplate: WorkflowTemplate = {
  id: 'defence-disclosure',
  name: 'Defence Disclosure',
  description: 'Ontario/Canada defence-support workflow for criminal disclosure, fraud matters, OSC crossover issues, motions/factums, and forensic accounting reports. Produces counsel-ready, citation-backed litigation-support work product.',
  steps: [
    'intake',
    'document_inventory',
    'procedural_frame',
    'disclosure_review',
    'element_proof_matrix',
    'forensic_accounting_review',
    'contradiction_gap_analysis',
    'crown_osc_red_team',
    'counsel_ready_synthesis',
    'final_gate',
    'delivered',
  ],
  stepDefinitions: {
    intake: {
      name: 'intake',
      description: 'Confirm Ontario/Canada defence-support scope, forum, status, charges/issues, documents, counsel-supervision assumption, and safety boundaries.',
      preconditions: [],
    },
    document_inventory: {
      name: 'document_inventory',
      description: 'Inventory disclosure, filings, expert reports, source data, unreadable items, and missing materials.',
      preconditions: ['intake'],
      qualityCheckType: 'self',
      maxIterations: 2,
    },
    procedural_frame: {
      name: 'procedural_frame',
      description: 'Frame Criminal Code, Charter/disclosure, OSC crossover, civil/receiver, and forum-specific procedural issues as research leads and counsel questions.',
      preconditions: ['document_inventory'],
    },
    disclosure_review: {
      name: 'disclosure_review',
      description: 'Review disclosure for chronology, source support, contradictions, late disclosure, redactions, chain-of-custody, and reproducibility issues.',
      preconditions: ['procedural_frame'],
      qualityCheckType: 'peer',
      qualityCheckerRole: 'criminal-defence-counsel',
      maxIterations: 2,
    },
    element_proof_matrix: {
      name: 'element_proof_matrix',
      description: 'Map each charge or issue to Crown/OSC theory, available proof, missing support, assumptions, and defence questions.',
      preconditions: ['disclosure_review'],
    },
    forensic_accounting_review: {
      name: 'forensic_accounting_review',
      description: 'Critique loss, tracing, source-of-funds, transaction, restitution, and expert-report methodology where financial records are present.',
      preconditions: ['element_proof_matrix'],
    },
    contradiction_gap_analysis: {
      name: 'contradiction_gap_analysis',
      description: 'Consolidate contradiction chart, disclosure gap list, unsupported calculations, and counsel question bank.',
      preconditions: ['forensic_accounting_review'],
    },
    crown_osc_red_team: {
      name: 'crown_osc_red_team',
      description: 'Steel-man Crown/OSC theory, test defence-side assumptions, and identify where the record remains adverse or incomplete.',
      preconditions: ['contradiction_gap_analysis'],
      qualityCheckType: 'peer',
      qualityCheckerRole: 'red-team',
      maxIterations: 1,
    },
    counsel_ready_synthesis: {
      name: 'counsel_ready_synthesis',
      description: 'Produce counsel-ready synthesis with inventory, chronology, proof matrix, accounting critique, contradictions, gaps, and prioritized counsel questions.',
      preconditions: ['crown_osc_red_team'],
      requiresEvaluatorGate: true,
      maxRevisionLoops: 2,
    },
    final_gate: {
      name: 'final_gate',
      description: 'Human approval before delivery. Counsel must verify legal strategy, deadlines, filings, and advice.',
      preconditions: ['counsel_ready_synthesis'],
      requiresGateApproval: true,
      gateType: 'final_delivery',
    },
    delivered: {
      name: 'delivered',
      description: 'Deliver citation-backed defence-support work product and audit bundle.',
      preconditions: ['final_gate'],
    },
  },
  availableTools: [
    'Read', 'Grep', 'Glob', 'Task', 'TodoWrite',
    'mcp__shem__get_current_step',
    'mcp__shem__advance_step',
    'mcp__shem__get_workflow_history',
    'mcp__shem__submit_handoff',
    'mcp__shem__get_handoffs',
    'mcp__shem__post_finding',
    'mcp__shem__decline_to_find',
    'mcp__shem__post_challenge',
    'mcp__shem__post_response',
    'mcp__shem__get_findings',
    'mcp__shem__get_challenges',
    'mcp__shem__get_debate_summary',
    'mcp__shem__resolve_debate',
    'mcp__shem__get_unresolved_debates',
    'mcp__shem__query_institutional_memory',
    'mcp__shem__add_institutional_memory',
    'mcp__shem__load_matter_memory',
    'mcp__shem__save_matter_memory',
    'mcp__shem__query_precedents',
    'mcp__shem__save_precedent',
    'mcp__shem__search_knowledge_base',
    'mcp__shem__list_knowledge_base_collections',
    'mcp__shem__get_knowledge_base_entry',
    'mcp__shem__list_documents',
    'mcp__shem__read_document_section',
    'mcp__shem__search_document',
    'mcp__shem__request_approval',
    'mcp__shem__run_evaluator_gate',
    'mcp__shem__record_evaluation_result',
    'mcp__shem__run_quality_check',
    'mcp__shem__record_quality_result',
  ],
  requiredAgents: [
    'criminal-defence-counsel',
    'disclosure-analyst',
    'forensic-accounting-analyst',
    'motion-factum-analyst',
    'legal-researcher',
    'litigation-partner',
    'red-team',
    'plain-language-specialist',
    'evaluator',
    'ethics-reviewer',
  ],
  maxTeamSize: 14,
  orchestratorArchetype: 'orchestrator-professor',
  orchestratorPrompt: orchestratorDefenceDisclosurePrompt,
  phasePermissions: {
    intake: {
      denyTools: [
        'mcp__shem__post_finding',
        'mcp__shem__resolve_debate',
        'mcp__shem__run_evaluator_gate',
        'mcp__shem__record_evaluation_result',
        'mcp__shem__request_approval',
      ],
      reason: 'Intake phase: establish scope, safety boundaries, and documents before analysis.',
    },
    document_inventory: {
      denyTools: ['mcp__shem__resolve_debate', 'mcp__shem__request_approval'],
      reason: 'Inventory phase: gather sources and post cited gaps before resolving debates.',
    },
    counsel_ready_synthesis: {
      denyTools: ['mcp__shem__request_approval'],
      reason: 'Synthesis phase: complete evaluator gate before final human approval.',
    },
    final_gate: {
      denyTools: [
        'mcp__shem__post_finding',
        'mcp__shem__run_evaluator_gate',
        'mcp__shem__record_evaluation_result',
      ],
      reason: 'Final gate: only approval decisions and reading are appropriate.',
    },
    delivered: {
      denyTools: [
        'mcp__shem__post_finding',
        'mcp__shem__request_approval',
        'mcp__shem__run_evaluator_gate',
        'mcp__shem__record_evaluation_result',
      ],
      reason: 'Delivered: no new analysis after handoff.',
    },
  },
};

workflowRegistry.register(defenceDisclosureTemplate);
