/**
 * Local Analysis — On-device legal review for confidential documents.
 *
 * v2 (2026-04-27): clause-aware map-reduce analysis.
 *
 * The previous version sent the first 8 K characters of a document to a
 * single LLM call and asked the model both to (a) extract verbatim quotes
 * and (b) reason about every clause. Small models (Gemma 2 2B, Phi-3 3B,
 * Llama 3.2 3B) cut both corners: they emitted "..." quote placeholders,
 * tagged everything "info" severity, and produced generic boilerplate
 * concerns that could apply to any contract.
 *
 * v2 fixes the design so a 2-3B model can produce useful triage:
 *
 *   1. **Clause-boundary chunking.** We segment the document by
 *      matching `^N. <Title>` patterns, producing one chunk per clause
 *      (≈21 chunks for a typical JV agreement). The model sees full
 *      clause text, not a 18% truncation.
 *
 *   2. **Pre-extracted text.** The chunker pulls the verbatim text
 *      from the document and hands it to the model. The model never
 *      has to "quote" — it only analyses what it was given. Kills
 *      the "..." placeholder failure.
 *
 *   3. **Per-clause prompts.** One LLM call per clause keeps each
 *      input small and focused. Small models excel at narrow tasks.
 *
 *   4. **Force-structured concerns.** Each concern must reference a
 *      specific party / defined term / dollar amount or it's stripped.
 *
 *   5. **Severity budget.** A final synthesis pass re-allocates
 *      severities — the model can't escape into "everything is info".
 *
 *   6. **Synthesis pass.** A final LLM call merges per-clause findings
 *      into top-N risks, executive summary, and recommendations.
 *
 * Cost: $0 per document (local inference).
 */

import { config } from '../config.js';
import type { ClawProfile, WatchmanResult, WatchmanDocumentType } from './types.js';
import type { PrecedentBoard, PrecedentMatch } from './precedent-board.js';
import { readerTemplate } from './reader-templates.js';

// ── Result Types ─────────────────────────────────────────────────────────

export interface LocalAnalysisResult {
  /** Plain-language document summary */
  summary: string;
  /** Detected document type (NDA, contract, etc.) */
  documentType: string;
  /** Key clauses identified */
  clauses: ClauseAnalysis[];
  /** Risk flags with severity */
  risks: RiskItem[];
  /** Actionable recommendations */
  recommendations: string[];
  /** Always present — reminds users this was local analysis */
  confidenceNote: string;
  /** Model used for analysis */
  model: string;
  /** Lighthouse Phase 2: PREC-ids surfaced during the per-clause sweep
   *  (deduped across clauses). Empty when no precedent board was supplied. */
  precedentsConsulted?: string[];
  /** Lighthouse Phase 2: number of findings the grounding pass stripped
   *  for lacking document-text anchorage. */
  unanchoredStripped?: number;
}

export interface ClauseAnalysis {
  title: string;
  /** Exact clause text (extracted by the chunker, not generated by the model) */
  text: string;
  /** What to watch for */
  concern: string;
  severity: 'info' | 'minor' | 'major' | 'critical';
}

export interface RiskItem {
  description: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  /** Where in the document */
  citation: string;
}

// ── Clause Chunking ──────────────────────────────────────────────────────

interface ClauseChunk {
  /** "1", "2", … "21" */
  number: string;
  /** "Definitions and interpretation" */
  title: string;
  /** Verbatim text of the clause body, extracted from the parsed document. */
  body: string;
}

/**
 * Chunk a document by clause boundaries.
 *
 * Detects lines matching `<N>. <Title>` (e.g. "1. Definitions and interpretation",
 * "9. Cash Calls and Dilution") and treats everything from one such header
 * to the next as a single clause body.
 *
 * Falls back to a single chunk if no clause headers are detected (e.g. for
 * NDAs that aren't numbered, or short letters).
 */
function chunkByClauseBoundaries(text: string): ClauseChunk[] {
  const lines = text.split('\n');
  const chunks: ClauseChunk[] = [];
  let current: { number: string; title: string; body: string[] } | null = null;

  for (const line of lines) {
    const trimmed = line.trim();
    // Match "1.", "1.0.", "21." at line start with title capitalised
    const m = /^(\d{1,2})\.\s+([A-Z][^.]{2,80})$/.exec(trimmed);
    if (m) {
      if (current) {
        chunks.push({
          number: current.number,
          title: current.title,
          body: current.body.join('\n').trim(),
        });
      }
      current = { number: m[1], title: m[2], body: [] };
    } else if (current) {
      current.body.push(line);
    }
  }
  if (current) {
    chunks.push({
      number: current.number,
      title: current.title,
      body: current.body.join('\n').trim(),
    });
  }

  // Fallback: if no clause structure detected, treat the whole document as
  // a single chunk so the analyser still has something to work with.
  if (chunks.length === 0) {
    chunks.push({ number: '1', title: 'Document', body: text.trim() });
  }

  return chunks;
}

// ── Prompts ──────────────────────────────────────────────────────────────

const PER_CLAUSE_PROMPT = `You are a senior legal-risk analyst. You will receive ONE clause from a contract at a time. Your job: identify what could go wrong for the CLIENT under this specific clause.

Rules — failure to follow makes your output unusable:

1. Every "concern" you raise must reference at least ONE of:
     (a) a specific defined term from this contract (e.g. "Operator", "Cure Period", "Reserved Matter")
     (b) a specific party by name (e.g. "Hartogen", "Cobaridge")
     (c) a specific dollar amount, percentage, or time period from the clause text

   Concerns that say only "ensure clarity" or "verify terms are clear" are GENERIC and FORBIDDEN.

2. Severity rules — use the full scale, do not default to "info":
     - "critical" → potential loss > 10% of project value, or unrecoverable rights forfeiture
     - "major"    → recoverable but materially adverse outcome, or onerous mechanic
     - "minor"    → mild drafting risk, ambiguity worth flagging
     - "info"     → background / definitional only (use sparingly — most clauses have real risk)

3. If the clause is purely definitional or boilerplate, output an empty concerns array.

4. The "operative_text" field must be a verbatim 1-3 sentence excerpt FROM THE CLAUSE I gave you. Do NOT write "...". Do NOT paraphrase. Pick the most material sentence(s).

Output ONLY a JSON object with this exact structure:
{
  "clauseRiskSummary": "string (1-2 sentences specific to THIS clause, not generic)",
  "operative_text": "string (verbatim excerpt, 1-3 sentences, from this clause)",
  "concerns": [
    {
      "text": "string (specific concern referencing defined term / party / number)",
      "severity": "info" | "minor" | "major" | "critical",
      "references": ["string"]   // list the defined terms / amounts / parties this references
    }
  ],
  "favoursWhom": "operator" | "non-operator" | "neutral"
}`;

const SYNTHESIS_PROMPT = `You are the senior partner closing out a JV contract review. You have just received per-clause analyses from your team. Produce the executive summary.

Rules:

1. The "summary" field must be 2-3 sentences naming both parties, the project, the jurisdiction, and the single biggest exposure for the client.

2. The "documentType" must be specific (e.g. "Mining Joint Venture Agreement (NSW, unincorporated)" — not "Contract").

3. The "topRisks" array contains AT LEAST 3 and AT MOST 6 risks, drawn from the highest-severity concerns in the per-clause analyses. Each risk MUST reference a clause number.

4. The "recommendations" array contains 3-5 actions the client should take BEFORE the next board meeting. Each starts with an imperative verb ("Issue", "Demand", "Audit", "Reject", "Notify"). No "review and consider" — that is not advice.

Output ONLY a JSON object:
{
  "summary": "string",
  "documentType": "string",
  "topRisks": [
    {
      "description": "string",
      "severity": "low" | "medium" | "high" | "critical",
      "citation": "string (clause number, e.g. 'cl 9.3' or 'cl 18.2')"
    }
  ],
  "recommendations": ["string"]
}`;

// ── HTTP Helper ──────────────────────────────────────────────────────────

interface OllamaConfig {
  baseUrl: string;
  modelName: string;
  timeoutMs: number;
}

function resolveOllamaConfig(): OllamaConfig {
  const modelName =
    config.claw.localAnalysisModel ||
    config.claw.localModel ||
    config.local.defaultModel;

  if (!modelName) {
    throw new Error(
      'No local model configured. Set LAVERN_LOCAL_DEFAULT_MODEL (preferred) or LAVERN_LOCAL_MODEL in .env',
    );
  }

  const baseUrl = (config.claw.localModelUrl || config.local.baseUrl).replace(/\/$/, '');
  const timeoutMs = Number(process.env.LAVERN_CLAW_LOCAL_TIMEOUT_MS) || 900_000;
  return { baseUrl, modelName, timeoutMs };
}

async function ollamaJsonChat(
  cfg: OllamaConfig,
  systemPrompt: string,
  userMessage: string,
  maxTokens = 1500,
): Promise<unknown> {
  const response = await fetch(`${cfg.baseUrl}/v1/chat/completions`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: cfg.modelName,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userMessage },
      ],
      temperature: 0.1,
      max_tokens: maxTokens,
      response_format: { type: 'json_object' },
    }),
    signal: AbortSignal.timeout(cfg.timeoutMs),
  });

  if (!response.ok) {
    const text = await response.text().catch(() => '');
    throw new Error(`Local model returned ${response.status}: ${text.slice(0, 200)}`);
  }

  const data = await response.json() as { choices?: Array<{ message: { content: string } }> };
  const content = data.choices?.[0]?.message?.content;
  if (!content) throw new Error('Local model returned empty response');

  return safeJsonParse(content);
}

function safeJsonParse(content: string): unknown {
  try { return JSON.parse(content); } catch { /* try fallbacks */ }
  // markdown-fenced JSON
  const fenced = content.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenced) {
    try { return JSON.parse(fenced[1]); } catch { /* try last fallback */ }
  }
  // first balanced object
  const obj = content.match(/\{[\s\S]*\}/);
  if (obj) {
    try { return JSON.parse(obj[0]); } catch { /* fall through */ }
  }
  throw new Error('Local model returned malformed JSON');
}

// ── Per-Clause Analysis ──────────────────────────────────────────────────

interface ClauseFinding {
  clauseNumber: string;
  clauseTitle: string;
  clauseRiskSummary: string;
  operativeText: string;
  concerns: Array<{
    text: string;
    severity: 'info' | 'minor' | 'major' | 'critical';
    references: string[];
    /** Phase 2: Precedent ID that informed or was reconciled with this concern. */
    precedentMatch?: string;
    /** Phase 2: Set true by the grounding pass when the evidence cannot be
     *  anchored back to clause text. Stripped from the final result. */
    unanchored?: boolean;
  }>;
  favoursWhom: 'operator' | 'non-operator' | 'neutral';
  /** Phase 2: PREC-ids the model received as context for this clause. */
  precedentsInjected: string[];
}

/**
 * Build a precedent-context block for injection into a per-clause prompt.
 * Empty string when no relevant precedents — keeps prompt size minimal.
 *
 * Phase 5: confirmed precedents are tagged with [CONFIRMED] and listed
 * first; tentative precedents follow with [TENTATIVE]. The Reader is
 * told to weight confirmed positions higher than tentative ones.
 */
function precedentContextBlock(matches: PrecedentMatch[]): string {
  if (matches.length === 0) return '';
  // Sort: confirmed precedents first (the firm has settled on this position),
  // then by relevance score within each tier.
  const sorted = [...matches].sort((a, b) => {
    const aConf = (a.entry.status === 'confirmed') ? 1 : 0;
    const bConf = (b.entry.status === 'confirmed') ? 1 : 0;
    if (aConf !== bConf) return bConf - aConf;
    return b.relevanceScore - a.relevanceScore;
  });
  const lines = sorted.slice(0, 3).map(m => {
    const status = m.entry.status === 'confirmed' ? '[CONFIRMED]' : '[TENTATIVE]';
    const desc = m.entry.description.replace(/[\x00-\x1f]/g, ' ').slice(0, 180);
    return `- ${status} [${m.entry.id}] ${m.entry.patternName} — ${desc} (effectiveness ${(m.entry.effectivenessScore * 100).toFixed(0)}%, seen ${m.entry.timesUsed}x)`;
  });
  return [
    '',
    'PRIOR FIRM POSITIONS ON SIMILAR CLAUSES (advisory — the live document outranks):',
    ...lines,
    '[CONFIRMED] = the firm has settled on this position across multiple matters; weight it heavily unless the document\'s language plainly contradicts.',
    '[TENTATIVE] = the firm has flagged this pattern but not confirmed; treat as a hypothesis to test against the document.',
    'Reconcile your judgment with the firm\'s prior positions where the document supports it. If the document contains language INCONSISTENT with a prior position, trust the document and explain the divergence in your concern.',
    '',
  ].join('\n');
}

async function analyseClause(
  cfg: OllamaConfig,
  chunk: ClauseChunk,
  profile: ClawProfile,
  precedents: PrecedentMatch[] = [],
  /** Phase 6: document type drives template selection. Defaults to the
   *  generic template for unknown / legacy callers. */
  documentType: WatchmanDocumentType = 'other',
): Promise<ClauseFinding> {
  const precedentBlock = precedentContextBlock(precedents);
  // Phase 6: pick the per-clause prompt that matches the document type.
  // 'jv', 'nda', 'employment', 'lease', 'loan', 'saas', 'policy' each get a
  // focused prompt; 'other' falls through to the generic legal-risk prompt.
  const systemPrompt = readerTemplate(documentType);
  const userMessage = [
    `CLIENT: ${profile.company} (${profile.industry}, ${profile.jurisdiction})`,
    `CLIENT'S CONCERNS: ${profile.concerns.join(', ')}`,
    `DOCUMENT TYPE: ${documentType}`,
    `CLIENT'S ROLE: ${profile.preferences?.riskAppetite === 'aggressive' ? 'sophisticated counterparty' : 'risk-conscious participant'}`,
    precedentBlock,
    `=== CLAUSE ${chunk.number}: ${chunk.title} ===`,
    chunk.body,
    `=== END CLAUSE ${chunk.number} ===`,
    '',
    'Now produce your JSON analysis of THIS clause only.',
  ].join('\n');

  const raw = await ollamaJsonChat(cfg, systemPrompt, userMessage, 1200) as Record<string, unknown>;
  const concerns = Array.isArray(raw.concerns) ? raw.concerns : [];

  // Light heuristic: if the model's text mentions a precedent ID we passed
  // in (e.g., "PREC-ab12cd34"), tag the concern with that match.
  const knownIds = new Set(precedents.map(p => p.entry.id));
  function detectPrecedentMatch(text: string): string | undefined {
    if (knownIds.size === 0) return undefined;
    for (const id of knownIds) {
      if (text.includes(id)) return id;
    }
    return undefined;
  }

  return {
    clauseNumber: chunk.number,
    clauseTitle: chunk.title,
    clauseRiskSummary: typeof raw.clauseRiskSummary === 'string' ? raw.clauseRiskSummary : '',
    operativeText: typeof raw.operative_text === 'string' && raw.operative_text.length > 5
      ? raw.operative_text
      : chunk.body.slice(0, 400),
    concerns: concerns.map(c => {
      const cc = c as Record<string, unknown>;
      const text = typeof cc.text === 'string' ? cc.text : '';
      return {
        text,
        severity: validateSeverity(typeof cc.severity === 'string' ? cc.severity : undefined, 'minor'),
        references: Array.isArray(cc.references) ? cc.references.filter((r): r is string => typeof r === 'string') : [],
        precedentMatch: detectPrecedentMatch(text),
      };
    }).filter(c => c.text.length > 10 && isSpecificConcern(c.text, c.references)),
    favoursWhom: validateFavours(typeof raw.favoursWhom === 'string' ? raw.favoursWhom : undefined),
    precedentsInjected: precedents.map(p => p.entry.id),
  };
}

// ── Grounding Pass (Phase 2) ─────────────────────────────────────────────

/**
 * Strip findings whose evidence cannot be anchored back to clause text.
 *
 * Cheap deterministic check first: does the concern's text reference a
 * clause number, defined term, dollar amount, or party name that appears
 * in the clause body? If yes, anchored. If no, mark unanchored.
 *
 * For ambiguous cases, an optional LLM verification pass could be added —
 * but the deterministic pass alone catches the major class of hallucinated
 * concerns ("ensure clarity") that local Gemma sometimes emits.
 *
 * Returns the count of unanchored findings (which are marked, not removed
 * from the audit trail) so the deliverable can report transparency.
 */
function groundingPass(findings: ClauseFinding[]): number {
  let stripped = 0;
  for (const finding of findings) {
    const clauseBodyLower = finding.operativeText.toLowerCase();
    for (const concern of finding.concerns) {
      const tokens = concern.text.match(/\b(?:cl(?:ause)?\s*\d+(?:\.\d+)?|\$[\d,]+|\d+%|\b\d{4}\b|\b\d+\s*(?:days?|months?|years?)\b)/gi) ?? [];
      const refsAnchored = concern.references.some(r => clauseBodyLower.includes(r.toLowerCase()));
      const tokenAnchored = tokens.some(t => clauseBodyLower.includes(t.toLowerCase()));
      if (!refsAnchored && !tokenAnchored && concern.references.length === 0) {
        // No anchor — mark unanchored so synthesis can deprioritise.
        concern.unanchored = true;
        stripped++;
      }
    }
  }
  return stripped;
}

/**
 * Reject concerns that are generic boilerplate. A concern is "specific"
 * iff it references at least one defined term / party / number, OR contains
 * a numeric/dollar/percentage token in the text itself.
 */
function isSpecificConcern(text: string, references: string[]): boolean {
  if (references.length > 0) return true;
  // Allow concerns that mention a clause number, dollar amount, percent, party name, or year
  if (/\bcl(?:ause)?\s*\d/i.test(text)) return true;
  if (/\$\d|%|\b\d{4}\b|\b\d+\s*(?:days?|months?|years?)\b/i.test(text)) return true;
  if (/\b(?:Hartogen|Cobaridge|Operator|Participant|Cure Period|Sole Risk|Reserved Matter|Force Majeure)\b/i.test(text)) return true;
  return false;
}

// ── Synthesis ────────────────────────────────────────────────────────────

interface Synthesis {
  summary: string;
  documentType: string;
  topRisks: Array<{ description: string; severity: 'low' | 'medium' | 'high' | 'critical'; citation: string }>;
  recommendations: string[];
}

async function synthesise(
  cfg: OllamaConfig,
  findings: ClauseFinding[],
  filename: string,
  profile: ClawProfile,
): Promise<Synthesis> {
  // Compact summary of per-clause findings to feed into synthesis
  const compactFindings = findings.map(f => {
    const topConcerns = f.concerns
      .sort((a, b) => severityRank(b.severity) - severityRank(a.severity))
      .slice(0, 3);
    return [
      `cl ${f.clauseNumber} (${f.clauseTitle}) — favours ${f.favoursWhom}`,
      `  summary: ${f.clauseRiskSummary}`,
      ...topConcerns.map(c => `  [${c.severity}] ${c.text}`),
    ].join('\n');
  }).join('\n\n');

  const userMessage = [
    `DOCUMENT: ${filename}`,
    `CLIENT: ${profile.company} (${profile.industry}, ${profile.jurisdiction})`,
    `CLIENT'S CONCERNS: ${profile.concerns.join(', ')}`,
    '',
    'PER-CLAUSE FINDINGS FROM THE TEAM:',
    compactFindings,
    '',
    'Now produce the executive synthesis JSON.',
  ].join('\n');

  const raw = await ollamaJsonChat(cfg, SYNTHESIS_PROMPT, userMessage, 1500) as Record<string, unknown>;

  return {
    summary: typeof raw.summary === 'string' ? raw.summary : `Local analysis of ${filename}`,
    documentType: typeof raw.documentType === 'string' ? raw.documentType : 'Document',
    topRisks: Array.isArray(raw.topRisks) ? raw.topRisks.map(r => {
      const rr = r as Record<string, unknown>;
      return {
        description: typeof rr.description === 'string' ? rr.description : '',
        severity: validateRiskSeverity(typeof rr.severity === 'string' ? rr.severity : undefined, 'medium'),
        citation: typeof rr.citation === 'string' ? rr.citation : '',
      };
    }).filter(r => r.description.length > 0) : [],
    recommendations: Array.isArray(raw.recommendations)
      ? raw.recommendations.filter((s): s is string => typeof s === 'string' && s.length > 5)
      : [],
  };
}

// ── Main Entry Point ─────────────────────────────────────────────────────

/**
 * Analyse a document entirely on-device using a local model.
 *
 * v2 pipeline:
 *   1. Chunk the document by clause boundaries (clauseN. Title).
 *   2. For each clause, run a focused per-clause analysis prompt.
 *   3. Run a synthesis prompt that merges per-clause findings into the
 *      executive summary, top-N risks, and recommendations.
 *
 * @throws If the local model is unreachable or returns invalid output
 */
export interface AnalyzeLocallyOptions {
  /** Lighthouse Phase 2: precedent board to query for per-clause context.
   *  When omitted, Reader runs without precedent injection (legacy behavior). */
  precedentBoard?: PrecedentBoard;
  /** Lighthouse Phase 1+: Watchman triage result. Used to scope precedent
   *  search by documentType + jurisdiction. */
  watchman?: WatchmanResult;
}

export async function analyzeLocally(
  documentText: string,
  filename: string,
  profile: ClawProfile,
  log?: (msg: string) => void,
  opts?: AnalyzeLocallyOptions,
): Promise<LocalAnalysisResult> {
  const cfg = resolveOllamaConfig();
  const chunks = chunkByClauseBoundaries(documentText);

  log?.(`  → ${chunks.length} clause${chunks.length === 1 ? '' : 's'} detected`);

  // Optional precedent context — queried once by document type + jurisdiction.
  // Per-clause precedent matching could narrow this further by clause topic
  // (a Phase 2.1 enhancement); for now we use a single document-scoped query
  // so the Reader sees consistent firm context across clauses.
  let documentPrecedents: PrecedentMatch[] = [];
  if (opts?.precedentBoard && opts?.watchman) {
    try {
      documentPrecedents = opts.precedentBoard.search({
        documentType: opts.watchman.documentType,
        jurisdiction: opts.watchman.jurisdiction || profile.jurisdiction,
        limit: 5,
      });
      if (documentPrecedents.length > 0) {
        log?.(`  → ${documentPrecedents.length} precedent(s) loaded for context`);
      }
    } catch (err) {
      log?.(`    ⚠ precedent lookup failed (${err instanceof Error ? err.message : err}) — proceeding without`);
    }
  }

  // Phase 6: pick the Reader template based on Watchman's documentType.
  // Defaults to 'other' (generic) when no Watchman result is available
  // (legacy callers, or processing before lighthouse rolled out).
  const docType: WatchmanDocumentType = opts?.watchman?.documentType ?? 'other';
  if (opts?.watchman) {
    log?.(`  → reader template: ${docType} (Watchman conf ${opts.watchman.confidence.toFixed(2)})`);
  }

  const findings: ClauseFinding[] = [];
  for (const [i, chunk] of chunks.entries()) {
    log?.(`  → analysing cl ${chunk.number} (${chunk.title.slice(0, 50)}) — ${i + 1}/${chunks.length}`);
    try {
      // Inject the top-3 most-relevant precedents. We pass the document-scoped
      // list to every clause; the model decides which (if any) apply.
      const finding = await analyseClause(cfg, chunk, profile, documentPrecedents.slice(0, 3), docType);
      findings.push(finding);
    } catch (err) {
      log?.(`    ✗ cl ${chunk.number} failed: ${err instanceof Error ? err.message : err}`);
      // Carry on — partial analysis is still useful
    }
  }

  // Phase 2: deterministic grounding pass — strips concerns whose claims
  // cannot be anchored to clause text via clause-numbers, dollar amounts,
  // percentages, periods, or named references.
  const unanchoredStripped = groundingPass(findings);
  if (unanchoredStripped > 0) {
    log?.(`  → grounding pass: ${unanchoredStripped} unanchored finding(s) flagged`);
  }
  // Drop unanchored concerns from the per-clause findings so synthesis sees
  // only grounded material. The audit trail can be reconstructed from the
  // unanchoredStripped count if needed.
  for (const f of findings) {
    f.concerns = f.concerns.filter(c => !c.unanchored);
  }

  log?.(`  → synthesising executive summary (${findings.length} clause findings)`);
  let syn: Synthesis;
  try {
    syn = await synthesise(cfg, findings, filename, profile);
  } catch (err) {
    log?.(`  ✗ synthesis failed (${err instanceof Error ? err.message : err}) — falling back to per-clause aggregate`);
    syn = aggregateFallback(findings, filename);
  }

  // Convert per-clause findings into the legacy ClauseAnalysis shape
  const clauses: ClauseAnalysis[] = findings.map(f => {
    const top = f.concerns.sort((a, b) => severityRank(b.severity) - severityRank(a.severity))[0];
    return {
      title: `${f.clauseNumber}. ${f.clauseTitle}`,
      text: f.operativeText,
      concern: top
        ? top.text
        : (f.clauseRiskSummary || `Clause ${f.clauseNumber} reviewed — no specific concern raised.`),
      severity: top ? top.severity : 'info',
    };
  });

  // Dedupe precedent IDs surfaced into any clause's findings.
  const precedentsConsulted: string[] = Array.from(new Set(
    findings.flatMap(f => f.concerns.map(c => c.precedentMatch).filter((id): id is string => !!id))
      .concat(documentPrecedents.map(m => m.entry.id))
  ));

  // Phase 5 (lighthouse): reinforce precedents that were applied. Done here
  // so the board's effectiveness scores track local-Reader usage too, not
  // just frontier dispatch. Soft-fail — a precedent reinforce error must
  // never poison the deliverable.
  if (opts?.precedentBoard) {
    for (const precId of precedentsConsulted) {
      try {
        opts.precedentBoard.reinforce(precId, `local-${cfg.modelName}-${Date.now()}`, 0.05);
      } catch { /* non-fatal */ }
    }
  }

  return {
    summary: syn.summary,
    documentType: syn.documentType,
    clauses,
    risks: syn.topRisks,
    recommendations: syn.recommendations,
    confidenceNote:
      'This document was analysed entirely on-device using a local model. No content was transmitted externally. ' +
      'For complex legal matters, verify findings with qualified counsel.',
    model: cfg.modelName,
    precedentsConsulted: precedentsConsulted.length > 0 ? precedentsConsulted : undefined,
    unanchoredStripped: unanchoredStripped > 0 ? unanchoredStripped : undefined,
  };
}

function aggregateFallback(findings: ClauseFinding[], filename: string): Synthesis {
  // If synthesis crashed (e.g. model timed out on the final pass), produce
  // a usable result from the per-clause output alone.
  const allConcerns = findings.flatMap(f => f.concerns.map(c => ({ f, c })));
  const sorted = allConcerns.sort((a, b) => severityRank(b.c.severity) - severityRank(a.c.severity));
  const topRisks = sorted.slice(0, 5).map(({ f, c }) => ({
    description: c.text,
    severity: c.severity === 'critical' ? 'critical' as const
            : c.severity === 'major'    ? 'high' as const
            : c.severity === 'minor'    ? 'medium' as const
            : 'low' as const,
    citation: `cl ${f.clauseNumber}`,
  }));
  return {
    summary: `Local clause-by-clause analysis of ${filename} (${findings.length} clauses analysed).`,
    documentType: 'Contract',
    topRisks,
    recommendations: [],
  };
}

// ── Helpers ──────────────────────────────────────────────────────────────

function severityRank(s: string): number {
  return { critical: 4, major: 3, high: 3, minor: 2, medium: 2, info: 1, low: 1 }[s] ?? 0;
}

function validateSeverity(
  s: string | undefined,
  fallback: 'info' | 'minor' | 'major' | 'critical',
): 'info' | 'minor' | 'major' | 'critical' {
  const valid = ['info', 'minor', 'major', 'critical'];
  return valid.includes(s ?? '') ? (s as 'info' | 'minor' | 'major' | 'critical') : fallback;
}

function validateRiskSeverity(
  s: string | undefined,
  fallback: 'low' | 'medium' | 'high' | 'critical',
): 'low' | 'medium' | 'high' | 'critical' {
  const valid = ['low', 'medium', 'high', 'critical'];
  return valid.includes(s ?? '') ? (s as 'low' | 'medium' | 'high' | 'critical') : fallback;
}

function validateFavours(s: string | undefined): 'operator' | 'non-operator' | 'neutral' {
  if (s === 'operator' || s === 'non-operator' || s === 'neutral') return s;
  return 'neutral';
}

/**
 * Extract findings summary from local analysis result.
 * Maps local severity to the standard findings format.
 */
export function extractLocalFindings(
  result: LocalAnalysisResult,
): { critical: number; major: number; minor: number } {
  let critical = 0;
  let major = 0;
  let minor = 0;

  for (const clause of result.clauses) {
    if (clause.severity === 'critical') critical++;
    else if (clause.severity === 'major') major++;
    else minor++;
  }

  for (const risk of result.risks) {
    if (risk.severity === 'critical') critical++;
    else if (risk.severity === 'high') major++;
    else minor++;
  }

  return { critical, major, minor };
}
